export const appStatusMeta: Record<string, { code: string; status: string }> = {
  '/': { code: 'HOME-01', status: 'entry' },
  '/about': { code: 'DOC-01', status: 'profile' },
  '/writing': { code: 'ESS-01', status: 'published' },
  '/playground': { code: 'LAB-01', status: 'live' },
  '/playground/system': { code: 'UI-01', status: 'online' },
  '/playground/todo': { code: 'MF-01', status: 'online' },
  '/playground/uplink': { code: 'GM-01', status: 'online' },
  '/system': { code: 'UI-01', status: 'redirect' },
  '/todo': { code: 'MF-01', status: 'redirect' },
  '/game': { code: 'GM-01', status: 'redirect' },
  '/uses': { code: 'DOC-02', status: 'redirect' },
  '/uses/gear': { code: 'DOC-02', status: 'indexed' },
  '/readme': { code: 'DOC-01', status: 'redirect' },
};
