#!/usr/bin/env node

import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { findProjectRoot } from "workspace-tools";

const repoRoot = findProjectRoot(
  path.dirname(fileURLToPath(import.meta.url)),
  "pnpm",
);

const skillsScriptPath = path.join(repoRoot, "scripts", "skills.mjs");
const agentsPath = path.join(repoRoot, "AGENTS.md");
const claudeSkillsPath = path.join(repoRoot, ".claude", "skills");
const openskillsBinPath = path.join(
  repoRoot,
  "node_modules",
  ".bin",
  "openskills",
);

function runNode(args, options = {}) {
  return spawnSync("node", args, {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    ...options,
  });
}

function assertOk(result, context) {
  assert.equal(
    result.status,
    0,
    `${context}\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
  );
}

async function main() {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "playground-skills-smoke-"));
  const backup = {
    agents: await readFile(agentsPath, "utf8"),
    binExists: fs.existsSync(openskillsBinPath),
    binContents: fs.existsSync(openskillsBinPath)
      ? await readFile(openskillsBinPath, "utf8")
      : null,
  };
  const uniqueSkillName = `smoke-wrapper-skill-${Date.now()}`;
  const sourceRoot = path.join(tempDir, "source");
  const sourceSkillDir = path.join(sourceRoot, uniqueSkillName);

  try {
    await rm(sourceRoot, { recursive: true, force: true });
    await mkdir(sourceSkillDir, { recursive: true });
    await mkdir(path.dirname(openskillsBinPath), { recursive: true });
    await writeFile(
      path.join(sourceSkillDir, "SKILL.md"),
      `# ${uniqueSkillName}\n\nSmoke test skill.\n`,
      "utf8",
    );

    await writeFile(
      openskillsBinPath,
      `#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");

const repoRoot = ${JSON.stringify(repoRoot)};
const stubStorePath = ${JSON.stringify(path.join(tempDir, "stub-store"))};

function firstPositionalArg(values) {
  return values.find((value) => !value.startsWith("-")) ?? null;
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function copyDir(sourceDir, targetDir) {
  ensureDir(targetDir);
  for (const entry of fs.readdirSync(sourceDir, { withFileTypes: true })) {
    const sourcePath = path.join(sourceDir, entry.name);
    const targetPath = path.join(targetDir, entry.name);
    if (entry.isDirectory()) {
      copyDir(sourcePath, targetPath);
      continue;
    }
    fs.copyFileSync(sourcePath, targetPath);
  }
}

const [command, ...args] = process.argv.slice(2);

switch (command) {
  case "install": {
    const source = firstPositionalArg(args);
    if (!source) {
      console.error("stub install requires source");
      process.exit(1);
    }
    const sourceRoot = path.resolve(repoRoot, source);
    const entries = fs.readdirSync(sourceRoot, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) {
        continue;
      }
      const skillDir = path.join(sourceRoot, entry.name);
      if (!fs.existsSync(path.join(skillDir, "SKILL.md"))) {
        continue;
      }
      copyDir(skillDir, path.join(stubStorePath, entry.name));
    }
    break;
  }
  case "list": {
    const skills = fs
      .readdirSync(stubStorePath, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
    process.stdout.write(\`\${skills.join("\\n")}\\n\`);
    break;
  }
  case "read": {
    const skillName = firstPositionalArg(args);
    if (!skillName) {
      console.error("stub read requires skill name");
      process.exit(1);
    }
    process.stdout.write(
      fs.readFileSync(
        path.join(stubStorePath, skillName, "SKILL.md"),
        "utf8",
      ),
    );
    break;
  }
  case "sync": {
    const outputIndex = args.findIndex(
      (arg) => arg === "--output" || arg === "-o",
    );
    if (outputIndex === -1 || !args[outputIndex + 1]) {
      console.error("stub sync requires --output");
      process.exit(1);
    }
    const outputPath = args[outputIndex + 1];
    fs.writeFileSync(
      outputPath,
      [
        "# Generated by stub",
        "",
        "<skills_system>",
        "Use npx openskills read <skill-name> to inspect a skill.",
        "</skills_system>",
        "",
      ].join("\\n"),
      "utf8",
    );
    break;
  }
  default:
    console.error(\`Unsupported stub command: \${command}\`);
    process.exit(1);
}
`,
      "utf8",
    );
    fs.chmodSync(openskillsBinPath, 0o755);

    const symlinkStat = fs.lstatSync(claudeSkillsPath);
    assert.equal(symlinkStat.isSymbolicLink(), true, ".claude/skills must stay a symlink");

    const installResult = runNode([skillsScriptPath, "install", sourceRoot]);
    assertOk(installResult, "skills install should succeed");

    const listResult = runNode([skillsScriptPath, "list"]);
    assertOk(listResult, "skills list should succeed");
    assert.match(listResult.stdout, new RegExp(`^${uniqueSkillName}$`, "m"));

    const readResult = runNode([skillsScriptPath, "read", uniqueSkillName]);
    assertOk(readResult, "skills read should succeed");
    assert.match(readResult.stdout, new RegExp(uniqueSkillName));

    const syncResult = runNode([skillsScriptPath, "sync"]);
    assertOk(syncResult, "skills sync should succeed");
    const mergedAgents = await readFile(agentsPath, "utf8");
    assert.match(mergedAgents, /<skills_system>/);
    assert.match(mergedAgents, /pnpm skills:read <skill-name>/);
    assert.doesNotMatch(mergedAgents, /npx openskills read <skill-name>/);
  } finally {
    await writeFile(agentsPath, backup.agents, "utf8");
    await rm(sourceRoot, { recursive: true, force: true });
    await rm(tempDir, { recursive: true, force: true });

    if (backup.binExists && backup.binContents != null) {
      await writeFile(openskillsBinPath, backup.binContents, "utf8");
      fs.chmodSync(openskillsBinPath, 0o755);
    } else {
      await rm(openskillsBinPath, { force: true });
    }
  }
}

await main();
